/**
 * Minimal Codex app-server protocol surface used by Craft Agents.
 *
 * The app-server API is experimental. These structural types intentionally
 * cover only messages we send or render and are based on the TypeScript
 * definitions generated by codex-cli 0.154.x.
 */

export type JsonValue = null | boolean | number | string | JsonValue[] | { [key: string]: JsonValue };
export type RequestId = string | number;

export interface JsonRpcRequest {
  jsonrpc: '2.0';
  id: RequestId;
  method: string;
  params?: unknown;
}

export interface JsonRpcResponse {
  jsonrpc: '2.0';
  id: RequestId;
  result?: unknown;
  error?: { code: number; message: string; data?: unknown };
}

export interface JsonRpcNotification {
  jsonrpc: '2.0';
  method: string;
  params?: unknown;
}

export type JsonRpcMessage = JsonRpcRequest | JsonRpcResponse | JsonRpcNotification;

export interface InitializeParams {
  clientInfo: { name: string; title: string | null; version: string };
  capabilities: {
    experimentalApi: boolean;
    requestAttestation: boolean;
    optOutNotificationMethods?: string[] | null;
    extensions?: Record<string, JsonValue> | null;
  } | null;
}

export interface InitializeResponse {
  userAgent: string;
  codexHome: string;
  platformFamily: string;
  platformOs: string;
}

export type AskForApproval = 'untrusted' | 'on-request' | 'never';
export type SandboxMode = 'read-only' | 'workspace-write' | 'danger-full-access';
export type ReasoningEffort = 'minimal' | 'low' | 'medium' | 'high' | 'xhigh' | 'ultra';

export interface DynamicToolSpec {
  type: 'function';
  name: string;
  description: string;
  inputSchema: JsonValue;
  deferLoading?: boolean;
}

export type UserInput =
  | { type: 'text'; text: string; text_elements: [] }
  | { type: 'image'; url: string; detail?: 'auto' | 'low' | 'high' | 'original' }
  | { type: 'localImage'; path: string; detail?: 'auto' | 'low' | 'high' | 'original' };

export interface ThreadStartParams {
  model?: string | null;
  cwd?: string | null;
  runtimeWorkspaceRoots?: string[] | null;
  approvalPolicy?: AskForApproval | null;
  sandbox?: SandboxMode | null;
  baseInstructions?: string | null;
  developerInstructions?: string | null;
  ephemeral?: boolean | null;
  dynamicTools?: DynamicToolSpec[] | null;
  experimentalRawEvents?: boolean;
}

export interface ThreadResponse {
  thread: { id: string; turns?: Turn[] };
  model: string;
  cwd: string;
}

export interface ThreadResumeParams extends ThreadStartParams {
  threadId: string;
  excludeTurns?: boolean;
}

export interface TurnStartParams {
  threadId: string;
  input: UserInput[];
  cwd?: string | null;
  runtimeWorkspaceRoots?: string[] | null;
  approvalPolicy?: AskForApproval | null;
  model?: string | null;
  effort?: ReasoningEffort | null;
  outputSchema?: JsonValue | null;
}

export interface TurnSteerParams {
  threadId: string;
  input: UserInput[];
  expectedTurnId: string;
}

export interface Turn {
  id: string;
  status: 'completed' | 'interrupted' | 'failed' | 'inProgress';
  error: { message: string; additionalDetails?: string | null } | null;
  items: ThreadItem[];
}

export interface TurnStartResponse { turn: Turn }

export interface TokenUsageBreakdown {
  totalTokens: number;
  inputTokens: number;
  cachedInputTokens: number;
  cacheWriteInputTokens: number;
  outputTokens: number;
  reasoningOutputTokens: number;
}

export interface ThreadTokenUsageUpdatedNotification {
  threadId: string;
  turnId: string;
  tokenUsage: {
    total: TokenUsageBreakdown;
    last: TokenUsageBreakdown;
    modelContextWindow: number | null;
  };
}

export type ThreadItem =
  | { type: 'userMessage'; id: string; content: UserInput[] }
  | { type: 'agentMessage'; id: string; text: string }
  | { type: 'reasoning'; id: string; summary: string[]; content: string[] }
  | {
      type: 'commandExecution'; id: string; command: string; cwd: string;
      status: 'inProgress' | 'completed' | 'failed' | 'declined';
      aggregatedOutput: string | null; exitCode: number | null;
    }
  | {
      type: 'fileChange'; id: string;
      changes: Array<{ path: string; kind: unknown; diff: string }>;
      status: 'inProgress' | 'completed' | 'failed' | 'declined';
    }
  | {
      type: 'mcpToolCall'; id: string; server: string; tool: string;
      arguments: JsonValue; status: string; result: unknown; error: { message: string } | null;
    }
  | {
      type: 'dynamicToolCall'; id: string; namespace: string | null; tool: string;
      arguments: JsonValue; status: 'inProgress' | 'completed' | 'failed';
      contentItems: DynamicToolOutputItem[] | null; success: boolean | null;
    }
  | { type: 'webSearch'; id: string; query: string; results: JsonValue[] | null }
  | { type: 'imageView'; id: string; path: string };

export interface ItemNotification {
  threadId: string;
  turnId: string;
  item: ThreadItem;
}

export interface TextDeltaNotification {
  threadId: string;
  turnId: string;
  itemId: string;
  delta: string;
}

export interface TurnCompletedNotification { threadId: string; turn: Turn }

export interface DynamicToolCallParams {
  threadId: string;
  turnId: string;
  callId: string;
  namespace: string | null;
  tool: string;
  arguments: JsonValue;
}

export type DynamicToolOutputItem =
  | { type: 'inputText'; text: string }
  | { type: 'inputImage'; imageUrl: string }
  | { type: 'inputAudio'; audioUrl: string };

export interface DynamicToolCallResponse {
  contentItems: DynamicToolOutputItem[];
  success: boolean;
}

export interface CommandApprovalParams {
  threadId: string;
  turnId: string;
  itemId: string;
  command?: string | null;
  cwd?: string | null;
  reason?: string | null;
}

export interface FileChangeApprovalParams {
  threadId: string;
  turnId: string;
  itemId: string;
  reason?: string | null;
  grantRoot?: string | null;
}

export interface PermissionsApprovalParams {
  threadId: string;
  turnId: string;
  itemId: string;
  reason: string | null;
  permissions: Record<string, JsonValue | null>;
}

export interface ChatgptAuthTokensRefreshParams {
  reason: string;
  previousAccountId?: string | null;
}

export interface AccountReadResponse {
  account: { type: string; [key: string]: unknown } | null;
  requiresOpenaiAuth: boolean;
}
