export const improvementStrings = {
  thinkingRecommendation: ['建议默认强度：{{level}}。整理与指定检查用 low，一般分析用 medium，开发与复核用 high，困难任务再用 xhigh / max。', 'Suggested default: {{level}}. Use low for extraction and specified checks, medium for general analysis, high for development and review, and xhigh / max for difficult tasks.'],
  applyThinkingRecommendation: ['采用建议强度', 'Apply suggested level'],
  taskThinkingEnabled: ['允许按任务选择思考强度', 'Allow thinking level per task'],
  taskThinkingHint: ['编排与手动派工可以覆盖本次任务；后续任务恢复节点默认值。实际支持范围由模型后端决定。', 'Planning and manual assignment can override this task. Later tasks use the node default. Actual support depends on the model backend.'],
  nodeThinkingDefault: ['沿用节点默认', 'Use node default'],
  taskAcceptance: ['验收条件（每行一项）', 'Acceptance criteria (one per line)'],
  taskAcceptanceHint: ['代码、科研、运维的产出任务必须填写可验证条件，并由其他节点复核。', 'Coding, research and operations output tasks require verifiable criteria and review by another worker.'],
  reviewWorkersRequired: ['独立复核需要至少两个工作节点。', 'Independent review requires at least two workers.'],
  requirements: ['执行条件检查', 'Execution readiness'],
  requiredPrograms: ['镜像所需程序（逗号分隔）', 'Required image programs (comma separated)'],
  requiredProgramsHint: ['按项目填写 git、bun、node、python3 等。无沙箱时检查宿主 PATH，受限控制需逐次批准运行；使用容器时镜像与离线依赖需预先准备。', 'Specify project tools such as git, bun, node or python3. Without a sandbox, check the host PATH and approve each run in restricted control. Prepare container images and offline dependencies in advance.'],
  requireBrowser: ['此方案需要浏览器执行客户端', 'This setup requires a browser client'],
  checkEnvironment: ['检查执行条件', 'Check execution readiness'],
  checkEnvironmentHint: ['检查在执行服务器进行：核对目录、所需程序和浏览器连接。无沙箱时仅查找 PATH 中的程序文件，不执行；容器模式使用无项目挂载的临时容器，不下载镜像。', 'Checks run on the execution server: folder, required programs and browser connection. Host checks locate program files on PATH without execution. Container checks use a temporary container without project mounts or image downloads.'],
  readinessPassed: ['所声明的执行条件已满足', 'Declared execution requirements are met'],
  readinessFailed: ['执行条件尚未满足', 'Execution requirements are not met'],
  readinessScope: ['检查确认程序存在与当前连接可用；项目依赖、具体构建命令及外部账号仍需任务实际验证。环境变化后请重新检查。', 'Checks confirm program presence and current connectivity. Tasks must still verify project dependencies, build commands and external accounts. Check again after environment changes.'],
  statistics: ['运行统计', 'Run statistics'],
  statisticsHint: ['运行计数随工作区保存。任务与目标统计基于当前保留记录；用量按节点会话增量累计，缺失数据不按零费用推断。', 'Run counters persist with the workspace. Task and goal counts use retained records. Usage accumulates session deltas by node; missing data does not imply zero cost.'],
  statisticsSince: ['节点与用量统计开始于 {{time}}；此前的历史用量未回填。', 'Node and usage tracking began at {{time}}; earlier usage was not backfilled.'],
  modelTurns: ['模型轮次', 'Model turns'],
  toolCalls: ['工具调用', 'Tool calls'],
  retryCount: ['自动重试', 'Automatic retries'],
  resumeCount: ['检查点续做', 'Checkpoint resumptions'],
  executionTime: ['已结算执行时长', 'Settled execution time'],
  queueTime: ['累计首次排队时长', 'Total initial queue time'],
  retainedTasks: ['保留的任务', 'Retained tasks'],
  acceptedTasks: ['已验收任务', 'Accepted tasks'],
  failedTasks: ['失败 / 已取消任务', 'Failed / cancelled tasks'],
  deliveredGoals: ['已交付目标', 'Delivered goals'],
  observedOutputTokens: ['已记录输出 token', 'Recorded output tokens'],
  recordedCost: ['已记录模型费用（USD）', 'Recorded model cost (USD)'],
  usageCoverage: ['{{count}} / {{total}} 个启动轮次返回了可累计的输出用量。费用只计已报告数据，可能不完整；不包含外部工具消费，供应商账单为准。', '{{count}} / {{total}} started turns returned cumulative output usage. Costs include reported data only, may be incomplete and exclude external tool charges. Provider invoices are authoritative.'],
  noUsage: ['未取得数据', 'No data reported'],
  noStatistics: ['尚无新增运行统计', 'No new run statistics yet'],
  failures: ['失败 / 中断轮次', 'Failed / interrupted turns'],
} as const
