'use strict'
const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')
const os = require('node:os')
const { pathToFileURL } = require('node:url')
const { getEventListeners } = require('node:events')
require('./dist/app/runtime/compat.cjs')
const temp = fs.mkdtempSync(path.join(os.tmpdir(), 'win7 preload with spaces 中文-'))
const preload = path.join(temp, 'compat.cjs')
fs.copyFileSync(path.join(__dirname, 'dist/app/runtime/compat.cjs'), preload)
process.env.TOKENBIRD_WIN7_PRELOAD = preload
async function main() {
  assert.equal(process.versions.node, '16.17.1')
  const first = new AbortController()
  const second = new AbortController()
  const combined = AbortSignal.any([first.signal, first.signal, second.signal])
  assert.equal(getEventListeners(first.signal, 'abort').length, 1)
  second.abort('smoke cancellation')
  assert.equal(combined.reason, 'smoke cancellation')
  assert.equal(getEventListeners(first.signal, 'abort').length, 0)
  assert.equal(AbortSignal.any([second.signal]).aborted, true)
  assert.throws(() => AbortSignal.any([first.signal, {}]), TypeError)
  const object = { value: new Map([['a', 1]]) }
  assert.equal(structuredClone(object).value.get('a'), 1)
  assert.equal(new Headers({ Test: 'pass' }).get('test'), 'pass')
  const { getRandomValues } = await import(pathToFileURL(path.join(__dirname, 'compat-crypto.mjs')).href)
  assert.equal(getRandomValues(new Uint8Array(8)).length, 8)
  const { spawn } = await import(pathToFileURL(path.join(__dirname, 'compat-child-process.mjs')).href)
  const child = spawn(process.execPath, ['-e', 'process.stdout.write(JSON.stringify({ node: process.versions.node, fetch: typeof fetch, abortAny: typeof AbortSignal.any }))'])
  let output = ''; let error = ''
  child.stdout.on('data', chunk => { output += chunk })
  child.stderr.on('data', chunk => { error += chunk })
  const code = await new Promise(resolve => child.once('exit', resolve))
  assert.equal(code, 0, error)
  assert.deepEqual(JSON.parse(output), { node: '16.17.1', fetch: 'function', abortAny: 'function' })
  console.log(JSON.stringify({ success: true, node: process.versions.node, abortListenersCleaned: true, unicodeAndSpacePreloadPath: true }))
}
main().catch(error => { console.error(error.stack); process.exitCode = 1 })
